export const Segments = [
  'Saúde/bem-star',
  'Casa/construção',
  'Alimentação',
  'Transporte/logística',
  'Tecnologia',
  'Educação',
  'Viagem/turismo',
  'Finanças/investimentos',
  'Pets',
  'Publicidade/propaganda',
  'Industria',
  'Juridico/advocacia',
  'Consultoria/gestão empresarial',
  'Limpeza/higiene',
  'Reciclagem/resíduos',
  'Artesanato',
  'Brinquedos/jogos',
  'Instrumentos musicais',
  'Eventos',
  'Outros',
];
